### ISSUE TITLE
Java IoT SDK unable to connect to the broker

### ISSUE THREAD

**Issue by german-sviridov** [german-sv/comsys19#1]
When using AWS IoT Device SDK for Java the MQTT client is unable to connect.

**Comment by german-sv** [comment]
[connect_device_package.zip](https://github.com/german-sv/comsys19/files/3265638/connect_device_package.zip)

**Comment by MarcoFlo** [comment]
Era una cavolata senza precedenti:
`# Client ID, unique client ID per connection `
`clientId=sdk-java`
una stringa random non va bene, bisogna proprio mettere sdk-java che di unique non so cosa abbia

**Comment by german-sviridov** [comment]
Will add to the documentation in the FAQ section. Thanks!

**Comment by MarcoFlo** [comment]
Adesso però le cose strane sono due:
- Non ricevo nessun messaggio ogni minuto sul topic pl19/notification
- Senza inserire il mac del mio dispositivo, riesco a fare la publish e a ricevere il relativo msg

**Comment by MarcoFlo** [comment]
Okay adesso i messaggi stanno arrivando (dalle 17.06)
